### ISSUE TITLE
check: password should never be present in "puts"

### ISSUE THREAD

**Issue by MichaelDimmitt** [murjax/Github-Repo-Submodulizer#10]

**Comment by MichaelDimmitt** [comment]
password logic is usually a one line git command. 
We still might want to have password logic exist in a method ... to ensure password safety. 
Which would resolve this issue.

**Comment by murjax** [comment]
Credentials are displayed when commits are pushed to Github. We want to remove puts from the git push commands.

**Comment by MichaelDimmitt** [comment]
we handled this with a 		`git push origin master --quiet`
