### ISSUE TITLE
add Clone down based on folder name user enters.

### ISSUE THREAD

**Issue by MichaelDimmitt** [murjax/Github-Repo-Submodulizer#23]
In building this command 
we could check online first... if not on github... check my_repositories folder. 
we could put an exit character like "-l " to specify local folder.

**Comment by murjax** [comment]
Method has been added. For now, the method checks if it exists remotely and clones down if it does. Otherwise the script continues assuming it's all local. We still need to add a handle for the case where the master folder is not found remotely or locally.

**Comment by MichaelDimmitt** [comment]
Lets make testing and implementing when nothing found a new issue.
