### ISSUE TITLE
(handle Folder not found.) both online and offline

### ISSUE THREAD

**Issue by MichaelDimmitt** [murjax/Github-Repo-Submodulizer#29]
When nothing online to clone and not in environment folder.

should prompt user folder name not found. 
enter new folder name?

first fix: Program will state "folder not found" and terminate.
second fix: will reprompt folder name.

**Comment by MichaelDimmitt** [comment]
testing and implementing when nothing online to clone and not in environment folder.

**Comment by MichaelDimmitt** [comment]
<h1>Example:</h1>
<pre>
Michaels-MacBook-Pro-3:Github-Repo-Submodulizer zen1$ rake submodulize_folder
Please enter folder name: 
alidhoaiwhopdihaoewifdh
Please enter Github account name for master repository: 
MichaelDimmitt
Please enter password for master Github account: 
Please enter Github account name for junk repository: 
miketestgit01
Please enter password for junk Github account: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2165  100  2165    0     0   4798      0 --:--:-- --:--:-- --:--:--  4800
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2165  100  2165    0     0   9952      0 --:--:-- --:--:-- --:--:--  9931
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    87  100    87    0     0    423      0 --:--:-- --:--:-- --:--:--   424
cp: alidhoaiwhopdihaoewifdh: No such file or directory

rake aborted!
Errno::ENOENT: No such file or directory @ dir_chdir - my_repositories/alidhoaiwhopdihaoewifdh
/Library/aProjects/Environment/Github-Repo-Submodulizer/methods.rb:66:in `chdir'
/Library/aProjects/Environment/Github-Repo-Submodulizer/methods.rb:66:in `surface_folder_level'
/Library/aProjects/Environment/Github-Repo-Submodulizer/methods.rb:100:in `initialize_submodule'
/Library/aProjects/Environment/Github-Repo-Submodulizer/methods.rb:115:in `automate'
/Library/aProjects/Environment/Github-Repo-Submodulizer/Rakefile.rb:28:in `block in <top (required)>'
/Users/zen1/.rvm/gems/ruby-2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/zen1/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/zen1/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => submodulize_folder
(See full trace by running task with --trace)
Michaels-MacBook-Pro-3:Github-Repo-Submodulizer zen1$ 
</pre>

**Comment by murjax** [comment]
Fixed with d02d9af.
