### ISSUE TITLE
Perform recursion ourselves; comment out method: clone_master(). Replace with method clone() 

### ISSUE THREAD

**Issue by MichaelDimmitt** [murjax/Github-Repo-Submodulizer#37]
We know that clone --recursive fails if users coming in have an errant submodule.
but normal 'git clone' at each level should work.
note: after we build it we will know. "Might create errant submodules"  because the clones get most current whereas the submodules link to a particular commit.

**Comment by murjax** [comment]
Master should be the only repository cloned down. The current method of recursion that occurs in the current revision of initialize_submodule (8954906bb03d69195d47130c3572cef1e4b8672d) fails as it attempts to clone master into every subfolder, thus adding itself to the map being created (among other issues). If it were changed to clone down each subfolder repo , we run into the potential for subfolders being overwritten by (possibly different) remote repos as master is being submodulized. Most of the time this won't occur as these repos won't exist on the destination account until we create them. In any case however, **we shouldn't even attempt to clone subfolder repos from the junk account to ensure the map created reflects master.** 

That said, the master repo should keep record about when its subfolders were submodulized. **If it's been submodulized once, it shouldn't occur again as there is a risk for folder loss and submodule corruption.**  This means our application is only responsible for maintaining the submodules it creates. It should not be responsible for errant submodules the user might bring in. These are a separate concern from the map the submodulizer creates. 

While we are not responsible for errant submodules from users, we do understand that this will effect recursive cloning of the map. We will need to build our own "desubmodulizer" with our own recursion to effectively return the mapped master repo to its original structure. The design of this tool will be specified in another issue later, however it will need to be based off of the submodules that were created as part of the map and not pre-existing submodules. Pre-existing submodules are the responsibility of the user to extract if the user chooses to use our tool. This way our map remains clean and free from external corruption.

**Comment by MichaelDimmitt** [comment]
Im I understanding you correct? (affirmative, or NO)

so `git clone' did not work

we have to use `git clone --recursive`?

**Comment by murjax** [comment]
Just git clone on master. No recursion necessary.
