### ISSUE TITLE
Notify if repo has no subfolders. (otherwise program does nothing)?

### ISSUE THREAD

**Issue by MichaelDimmitt** [murjax/Github-Repo-Submodulizer#4]
program will perform nothing if there are no subfolders.

**Comment by MichaelDimmitt** [comment]
I had a subfolder in the directory that did not have a subfile.
github when adding and committing on your master repo 
will not recognize a subfolder with nothing in it.

the subfile was made a repository… however was not recognized
as a subfolder … was not added to GitHub and was not made a submodule.

**Comment by MichaelDimmitt** [comment]
Unit test completed.

**Comment by murjax** [comment]
I will make a counter that increments when the application changes directories into the subfolders. If the counter is 0 then we display a message that indicates that no subfolders were found.

**Comment by murjax** [comment]
Counter has been added in the doStuff method on the questions_areas-of-interest branch. We may implement this to master at anytime.
