### ISSUE TITLE
(5.) remote ... no subfolders found.

### ISSUE THREAD

**Issue by MichaelDimmitt** [murjax/Github-Repo-Submodulizer#43]
happens both locally and remotely.

**Comment by murjax** [comment]
Cloning into 'VagrantBinding'...
remote: Counting objects: 41, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 41 (delta 14), reused 41 (delta 14), pack-reused 0
Unpacking objects: 100% (41/41), done.


No subfolders found in this repository. No actions were taken.

**Comment by MichaelDimmitt** [comment]
we removed submodulize error that was causing the trouble
